### ISSUE TITLE
Document compatible HSM hardware models

### ISSUE THREAD

**Issue by bosswissam** [square/subzero#177]
Hi Team

Would be great if information about the HSM spec that is more detailed than "Thales nCipher Solo XC low" is added to the documentation. Searching for "Thales nCipher Solo XC low" does not yield an exact match (there's "Thales nShield" but without knowing the specs it's hard to compare).

Does not have to be an exact model number, just which HSM devices this code is compatible with or if there is a way to test for compatibility without having to purchase the HSM would be great.

Thanks!

**Comment by alokmenghrajani** [comment]
We have been using Thales nCipher Solo XC low (sometimes referred to as base?). The difference between low/mid/high is speed & pricing. There is no functional differences. Our development environment is high, so we are 100% confident the code also works with the high model.

Keep in mind that the CodeSafe license is required and typically billed separately. The firmware version we currently use is 12.50.11 and we try to use the vendor's latest firmware/software except when we run into technical issues and rollback.

To the best of my knowledge, Thales' other nCipher products are supposed to only differ in form factor. Therefore, the code _should_ work out of the box with an Edge or a Connect. We can however not guarantee this since we don't own the other form factors.

I'll update the documentation to reflect this information.

**Comment by bosswissam** [comment]
Thanks @alokmenghrajani 

Yes I think the names might have changed which is what has been confusing for me - I am looking at [this product page](https://www.ncipher.com/products/general-purpose-hsms/nshield-solo) for them and it seems the closest naming-wise

In [their own press-release about subzero](https://www.ncipher.com/resources/case-studies/square-deploys-ncipher-security-hsms-to-fight-cyber-attackers-on-its-own-terms), they called the model "nCipher nShield Solo XC hardware security module".

I'm contacting their sales team as well just to see what exact models they have - their product page mentions a "series" but does not seem to list all options, at least not the base/low/mid/high that you mention.

**Comment by alokmenghrajani** [comment]
So their marketing material refers to the device as nShield but their software calls it nCipher. We are going to continue calling it nCipher since that's what shows up in things like Java import statements.

On https://www.ncipher.com/products/general-purpose-hsms/nshield-solo, click on Specifications. You'll see the XC Base, XC Mid and XC High in there.

**Comment by alokmenghrajani** [comment]
I updated https://subzero.readthedocs.io/en/master/physical_components/. Closing this ticket, but feel free to reopen if you have any other questions related to picking the right device.
