### ISSUE TITLE
What is recommended hardware for development/connecting to HSM

### ISSUE THREAD

**Issue by bosswissam** [square/subzero#192]
If I may ask, for development purposes, are you connecting the HSM via an external PCIe card enclosure or you actually have a laptop/server with enough space to fit an HSM?

Any model/make recommendations you can offer, without compromising your own security, would be much appreciated. Plenty of options to buy but would rather go with what is known to work.

**Comment by alokmenghrajani** [comment]
Subzero currently only supports one kind of HSM:

from https://subzero.readthedocs.io/en/master/physical_components/
> The code is currently tightly coupled to the nShield. We are open to contributions enabling support for alternative vendors.

For development purpose, you can either build the code without hardware support (https://subzero.readthedocs.io/en/master/running_without_hsm/), have a local HSM (if you have a PCI port or the USB form factor), or you can ssh tunnel and forward the right set of ports/setup your local machine properly (I can share instructions if you are interested in doing local development with a remote HSM).

I usually don't use the HSM if I'm working on java/. I usually port-forward if I'm working on core/.

**Comment by bosswissam** [comment]
Definitely interested in seeing instructions for local dev with remote HSM - will come in handy.

At the moment I have the PCIe HSM for testing, and making a decision on which device I'll use to install it to. Will either be a desktop box or a laptop with an external PCIe reader.

It sounds like in your set up you are using a desktop box and you connect remotely whenever HSM is needed?

**Comment by alokmenghrajani** [comment]
Correct, I remote into a desktop. In theory, I could dev with a server in a datacenter since we have remote card readers (they are an additional cost).

In practice, I like having the setup close enough that I go fiddle with it without forcing me to lug the hardware around all the time. The main operation you'll be doing is plugging various smart cards in. (our desktop is shared among a handful of engineers since we don't need to each have our dedicated desktop).

The desktop+remote ssh with laptop ends up being a good combination.
