### ISSUE TITLE
Hardcoded CodeSafe filename and version

### ISSUE THREAD

**Issue by bosswissam** [square/subzero#198]
`bootstrap.sh` includes a hardcoded version of CodeSafe Developer Kit ISO (`CodeSafe-linux64-dev-12.50.2.iso`). It should probably be listed in docs and/or parametrized.

**Comment by bosswissam** [comment]
Similar problem with `./install_scripts/0_post_install_nochroot` - hardcoded `/media/CodeSafe/linux/libc6_11/amd64/nfast/gccsrc/ppcdev.tar`

**Comment by alokmenghrajani** [comment]
That's by design. The upgrade process is typically painful (I'm working on getting a build with 12.63.0, which I expect to wrap up by august. Happy to review a PR if you get 12.63.0 working before me. In the meantime, we plan to use 12.50.2).

I doesn't make sense to support multiple versions. Time permitting, we should always aim to build with the latest CodeSafe release. Thankfully, these upgrades don't happen often. About two years went by between 12.50.2 and 12.63.0. Every minor version between these two were skipped because they were limited releases (I typically test limited releases in dev so we can report bugs, but we don't expect to use them in production).

**Comment by alokmenghrajani** [comment]
The docs at https://subzero.readthedocs.io/en/master/physical_components/ do list the firmware/vendor software we support. Again, happy to review a PR which bumps us to the latest version.

**Comment by bosswissam** [comment]
Interesting - I just received this code last week and it's `12.50.4`, not `12.63.0`. Perhaps because I'm on trial still. Yes will definitely do a PR once I'm all set, if I get there before you.

**Comment by alokmenghrajani** [comment]
You'll have to ask for specific versions. I have never had issue getting download links.

12.50.4 has issues with key migration utilities. I have no idea why they would provide a limited release to a trial customer ¯\_(ツ)_/¯. If I remember correctly, there are work around but the instructions as written will not work.

**Comment by bosswissam** [comment]
@alokmenghrajani good to know - any eta on `12.63.0` support? Also, will you be sticking with Linux 3.x kernel or bumping to 5+?

**Comment by alokmenghrajani** [comment]
I don't have any ETA for wrapping up 12.63.0. I started working on it a few weeks ago and then ran into a few issues which slowed me down. It might take a few months before I can get back to it for various personal reasons.

I'm going to add a page to our documentation list our past and future release cycle. We typically update all the dependencies every 3 to 6 months.

So far, we have been happy with CentOS7 (which has another ~4 years before it's EOL). CentOS8 is not on linux kernel 5+ so I doubt we'll be picking up 5+ anytime soon (unless someone gives us a good reason to not use CentOS).

**Comment by bosswissam** [comment]
hmm - @alokmenghrajani I was under the impression you could update the kernel while staying on CentOS 7, perhaps I was wrong.

Newer kernel versions allow thunderbolt support, which allow you to use a PCIe extension box + laptop instead of a server.

**Comment by alokmenghrajani** [comment]
There are kernels available packaged by third party. You could copy the package at build time (similar to how other dependencies are handled) and upgrade the kernel (you might have to upgrade both, the outer VM and inner VM since kickstart makes some assumptions).

Are you planning to use a laptop for production purpose or only for dev/testing?

**Comment by alokmenghrajani** [comment]
At this point, 12.63.0 is blocked on various bugs. 12.50.2 remains the recommended version until the vendor releases a fixed version.
